version: '3.8'
  
services:
  app:
    container_name: ionic
    build: .
    ports:
        - 8100:8100
        - 35729:35729
    volumes:
      - .:/home/node/app
    command: /bin/sh -c "while sleep 1000; do :; done"